spring:
  application:
    name: admin_page
  datasource:
    url: jdbc:mysql://ssg-java3.iptime.org:3306/playgrounddb
    username: playground
    password: db1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      max-lifetime: 60000
      minimum-idle: 5
      idle-timeout: 30000
      auto-commit: false

server:
  servlet:
    context-path: /admin

logging:
  level:
    root: info
    com.playground.admin_page: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.playground.admin_page.main.user.model.dto
  mapper-locations: classpath*:mappers/**/*-mapper.xml

